# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Raga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('arohanam', models.CharField(max_length=100, unique=True)),
                ('avarohanam', models.CharField(max_length=100, unique=True)),
                ('melakarta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ragas.Raga')),
            ],
        ),
    ]
