# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ragas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raga',
            name='melakarta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ragas.Raga'),
        ),
    ]
