# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-13 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragas', '0002_auto_20180513_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raga',
            name='arohanam',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='raga',
            name='avarohanam',
            field=models.CharField(max_length=100),
        ),
    ]
