# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragas', '0003_auto_20180513_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='raga',
            name='format_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
