# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-26 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragas', '0004_raga_format_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('formula', models.CharField(max_length=20)),
                ('affix', models.CharField(max_length=20)),
            ],
        ),
    ]
